# Generated by Django 4.1.1 on 2022-09-16 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),  # noqa: E501
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='number',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='posts/%Y/%m-%d/'),  # noqa: E501
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(blank=True, default='', max_length=60, null=True),  # noqa: E501
        ),
    ]
