# Generated by Django 4.1.1 on 2022-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_date_created_posts_number_alter_posts_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
